exchange:
  enableRateLimit: true
  name: binance
  options:
    adjustForTimeDifference: true
    defaultType: future
  rateLimit: 1200
model:
  cv_folds: 5
  filter_threshold: 0.1
  test_size: 0.2
monitoring:
  interval_seconds: 60
paths:
  enhanced_data: data/enhanced/
  logs: logs/
  models: models/
  processed_data: data/processed/
  raw_data: data/raw/
signals:
  min_strength: 3
symbols:
- BTC/USDT
- ETH/USDT
- BNB/USDT
- SOL/USDT
- XRP/USDT
- CAKE/USDT
- DOGE/USDT
- MEME/USDT
- WIF/USDT
- POPCAT/USDT
- LINK/USDT
- ALGO/USDT
- ZRX/USDT
- OP/USDT
- LDO/USDT
timeframes:
  base: 5m
  multi:
  - 1m
  - 5m
  - 15m
  - 1h
